// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGlDuoRr05F2bOKLglWR0nC9R_hv-DZek',
    appId: '1:505641564881:android:b1f073f05947909faf23f0',
    messagingSenderId: '505641564881',
    projectId: 'hrms-768c0',
    storageBucket: 'hrms-768c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6L8ZGQpPclWZVmT7XhNzol2kK6XqbHVo',
    appId: '1:505641564881:ios:022b5f0774c672cfaf23f0',
    messagingSenderId: '505641564881',
    projectId: 'hrms-768c0',
    storageBucket: 'hrms-768c0.firebasestorage.app',
    iosBundleId: 'com.example.hrms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd1FCIUO7dkxktejXqST-d3PM9uU33ecE',
    appId: '1:505641564881:web:09898311c7718d5aaf23f0',
    messagingSenderId: '505641564881',
    projectId: 'hrms-768c0',
    authDomain: 'hrms-768c0.firebaseapp.com',
    storageBucket: 'hrms-768c0.firebasestorage.app',
    measurementId: 'G-H11PYJSRG6',
  );
}
